import { StyleSheet } from 'react-native';
import { COLORS } from '../colors';
import { SPACING, BORDER_RADIUS } from '../spacing';

export const consultasStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.gray['100'] },
  header: { backgroundColor: COLORS.secondary['500'], paddingBottom: SPACING.md },
  headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: SPACING.md, paddingTop: SPACING.md },
  headerTitle: { fontSize: 24, fontWeight: '800', color: COLORS.white },
  tabs: { flexDirection: 'row', paddingHorizontal: SPACING.md, gap: SPACING.sm, marginTop: SPACING.sm },
  tab: { paddingHorizontal: SPACING.md, paddingVertical: SPACING.xs, borderRadius: BORDER_RADIUS.full, backgroundColor: 'rgba(255,255,255,0.2)' },
  tabActive: { backgroundColor: COLORS.white },
  tabText: { fontSize: 14, fontWeight: '600', color: 'rgba(255,255,255,0.8)' },
  tabTextActive: { color: COLORS.secondary['500'] },
  scroll: { flex: 1, paddingHorizontal: SPACING.md, paddingTop: SPACING.md },
  scrollContent: { paddingBottom: 100 },
  scheduleBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.primary['500'], borderRadius: BORDER_RADIUS.lg, padding: SPACING.md, gap: SPACING.sm, marginBottom: SPACING.md },
  scheduleBtnText: { color: COLORS.white, fontSize: 15, fontWeight: '700' },
  teleBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.secondary['500'], borderRadius: BORDER_RADIUS.lg, padding: SPACING.md, gap: SPACING.sm, marginBottom: SPACING.lg },
  teleBtnText: { color: COLORS.white, fontSize: 15, fontWeight: '700' },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: COLORS.secondary['500'], marginBottom: SPACING.sm },
  card: { backgroundColor: COLORS.white, borderRadius: BORDER_RADIUS.lg, padding: SPACING.md, marginBottom: SPACING.sm, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 2 },
  cardRow: { flexDirection: 'row', alignItems: 'center', gap: SPACING.md },
  dateBox: { width: 52, height: 52, borderRadius: BORDER_RADIUS.md, alignItems: 'center', justifyContent: 'center' },
  dateDay: { fontSize: 20, fontWeight: '800', color: COLORS.white },
  dateMon: { fontSize: 10, color: 'rgba(255,255,255,0.8)', fontWeight: '600' },
  cardContent: { flex: 1 },
  cardTitle: { fontSize: 15, fontWeight: '700', color: COLORS.secondary['500'] },
  cardSub: { fontSize: 12, color: COLORS.gray['500'], marginTop: 2 },
  cardBadge: { paddingHorizontal: SPACING.sm, paddingVertical: 3, borderRadius: BORDER_RADIUS.full, marginTop: SPACING.xs, alignSelf: 'flex-start' },
  cardBadgeText: { fontSize: 11, fontWeight: '600' },
  empty: { alignItems: 'center', paddingVertical: SPACING.xl },
  emptyText: { fontSize: 15, color: COLORS.gray['400'], marginTop: SPACING.sm },
  // Modal form
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: COLORS.white, borderTopLeftRadius: BORDER_RADIUS.xl, borderTopRightRadius: BORDER_RADIUS.xl, padding: SPACING.lg, paddingBottom: 40 },
  modalTitle: { fontSize: 20, fontWeight: '800', color: COLORS.secondary['500'], marginBottom: SPACING.lg, textAlign: 'center' },
  modalLabel: { fontSize: 13, fontWeight: '600', color: COLORS.gray['500'], marginBottom: SPACING.xs },
  modalInput: { borderWidth: 1.5, borderColor: COLORS.gray['200'], borderRadius: BORDER_RADIUS.md, height: 52, paddingHorizontal: SPACING.md, fontSize: 15, color: COLORS.secondary['500'], backgroundColor: COLORS.gray['100'], marginBottom: SPACING.md },
  modalBtn: { backgroundColor: COLORS.primary['500'], borderRadius: BORDER_RADIUS.md, height: 54, alignItems: 'center', justifyContent: 'center', marginTop: SPACING.sm },
  modalBtnText: { color: COLORS.white, fontSize: 16, fontWeight: '700' },
  modalCancelBtn: { alignItems: 'center', marginTop: SPACING.sm, padding: SPACING.sm },
  modalCancelText: { color: COLORS.gray['500'], fontSize: 14 },
});
