import { StyleSheet } from 'react-native';
import { COLORS } from '../colors';
import { SPACING, BORDER_RADIUS } from '../spacing';

export const vetProfileStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.gray['100'] },
  header: { backgroundColor: COLORS.secondary['500'], paddingHorizontal: SPACING.md, paddingBottom: SPACING.xl },
  avatarRow: { flexDirection: 'row', alignItems: 'center', gap: SPACING.md, marginTop: SPACING.md },
  avatar: { width: 72, height: 72, borderRadius: 36, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },
  headerInfo: { flex: 1 },
  name: { fontSize: 20, fontWeight: '700', color: COLORS.white },
  email: { fontSize: 13, color: 'rgba(255,255,255,0.75)', marginTop: 2 },
  crmvBadge: { alignSelf: 'flex-start', backgroundColor: COLORS.primary['500'], paddingHorizontal: SPACING.sm, paddingVertical: 3, borderRadius: BORDER_RADIUS.full, marginTop: SPACING.xs },
  crmvText: { color: COLORS.white, fontSize: 11, fontWeight: '600' },
  scroll: { paddingHorizontal: SPACING.md, paddingBottom: 100 },
  sectionRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: SPACING.lg, marginBottom: SPACING.sm },
  sectionTitle: { fontSize: 17, fontWeight: '700', color: COLORS.secondary['500'], marginTop: SPACING.lg, marginBottom: SPACING.sm },
  editLink: { fontSize: 14, color: COLORS.primary['500'], fontWeight: '600' },
  infoCard: { backgroundColor: COLORS.white, borderRadius: BORDER_RADIUS.lg, padding: SPACING.md, shadowColor: COLORS.black, shadowOpacity: 0.05, shadowRadius: 6, elevation: 1 },
  infoRow: { flexDirection: 'row', alignItems: 'center', gap: SPACING.md, paddingVertical: SPACING.sm },
  iconBox: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  infoLabel: { fontSize: 12, color: COLORS.gray['400'] },
  infoValue: { fontSize: 14, fontWeight: '500', color: COLORS.secondary['500'] },
  separator: { height: 1, backgroundColor: COLORS.gray['200'], marginLeft: 52 },
  // edit form
  editCard: { backgroundColor: COLORS.white, borderRadius: BORDER_RADIUS.lg, padding: SPACING.md, shadowColor: COLORS.black, shadowOpacity: 0.05, shadowRadius: 6, elevation: 1 },
  fieldLabel: { fontSize: 13, fontWeight: '600', color: COLORS.secondary['500'], marginBottom: 6 },
  fieldLabelGap: { fontSize: 13, fontWeight: '600', color: COLORS.secondary['500'], marginBottom: 6, marginTop: 12 },
  fieldInput: { borderWidth: 1.5, borderColor: COLORS.gray['200'], borderRadius: BORDER_RADIUS.md, paddingHorizontal: SPACING.sm, paddingVertical: 10, fontSize: 14, color: COLORS.secondary['500'], backgroundColor: COLORS.gray['100'] },
  fieldInputError: { borderColor: COLORS.primary['500'] },
  fieldError: { fontSize: 12, color: COLORS.primary['500'], marginTop: 4 },
  tipoRow: { flexDirection: 'row', gap: SPACING.sm, marginTop: 4 },
  tipoBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, paddingVertical: 10, borderRadius: BORDER_RADIUS.md, borderWidth: 1.5, borderColor: COLORS.secondary['500'] },
  tipoBtnActive: { backgroundColor: COLORS.secondary['500'], borderColor: COLORS.secondary['500'] },
  tipoBtnText: { fontSize: 13, fontWeight: '600', color: COLORS.secondary['500'] },
  tipoBtnTextActive: { color: COLORS.white },
  saveBtn: { marginTop: SPACING.md, backgroundColor: COLORS.secondary['500'], borderRadius: BORDER_RADIUS.md, paddingVertical: 14, alignItems: 'center' },
  saveBtnText: { color: COLORS.white, fontSize: 15, fontWeight: '700' },
  logoutBtn: { marginTop: SPACING.xl, backgroundColor: COLORS.primary['500'], borderRadius: BORDER_RADIUS.md, padding: SPACING.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  logoutIcon: { marginRight: 8 },
  logoutText: { color: COLORS.white, fontSize: 16, fontWeight: '600' },
});
